### ISSUE TITLE
Improve mint flow

### ISSUE THREAD

**Issue by holygits** [cennznet/litho#11]
Couples issues:
- [x] User has to sign 2 transactions (create collection and mint NFT)
- [ ] Initial transaction sign dialog is slow to present to user after clicking mint

**Comment by KarishmaBothara** [comment]
After setting the piñata keys.. I get the right CID/hash.. 
will look at why it take so long to get the extension pop up

**Comment by KarishmaBothara** [comment]
One of the things observed was.. When I try with local node over Nikau... It is not that slow.. The time is around 8-10 sec most of which is to uploading data on IPFS... soon after that extension appear for signing... may be it is cause of Nikau show (connection drop) many times

**Comment by holygits** [comment]
I don't think IPFS is the problem here, as the dialog transitions from IPFS to
<img width="451" alt="Screen Shot 2021-10-15 at 16 35 27" src="https://user-images.githubusercontent.com/5133901/137428301-482180b5-20ae-44ed-8df6-5d16793bfece.png">
seems like a hook is not firing properly
