### ISSUE TITLE
Unhandled undefined error "(reading 'startsWith')"

### ISSUE THREAD

**Issue by eupston** [cennznet/litho#131]
Small unhandled error when attempting to load undefined asset

![Screen Shot 2022-01-10 at 3 27 52 PM](https://user-images.githubusercontent.com/35315320/148849594-6b192f53-8e9c-4bbb-b7c8-452a66528b51.png)

**Comment by ken-centrality** [comment]
@eupston just scanning through the list and this has been reported in #46. Should we close it?

**Comment by eupston** [comment]
@ken-centrality oo yes definitely, let me close this. Musta skipped over it when I was checking the issues.
