### ISSUE TITLE
Add spinners for tx confirmation

### ISSUE THREAD

**Issue by holygits** [cennznet/litho#48]
Should add some spinners here
<img width="456" alt="Screen Shot 2021-10-13 at 15 38 54" src="https://user-images.githubusercontent.com/5133901/137057569-58302b21-b239-42ad-a352-0142a79f9691.png">

**Comment by aidan-starke** [comment]
![upload spinner](https://user-images.githubusercontent.com/52016903/139616297-109235c0-1162-4206-8a8a-d6fe1e652b42.png)

Display loading spinner when uploading & minting NFT

https://github.com/cennznet/litho/pull/110
